server:
  port: 8101

spring:
  application:
    name: exp-auth-system

  # 公共数据源配置（所有服务目前共用同一个库）
  datasource:
    url: jdbc:mysql://192.168.101.128:3306/exp_ubantudb?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 开发阶段自动建表/更新表结构，后期可以改成 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.128:8848
        username: nacos
        password: nacos

