server:
  port: 8101

spring:
  application:
    name: exp-auth-system
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.128:8848
        username: nacos
        password: nacos


