server:
  port: 8102

spring:
  application:
    name: exp-bid-contract
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.128:8848
        username: nacos
        password: nacos


